version: '2.1'
services:
  rubis:
    container_name: rubis
    build:
      context: ./Rubis
    ports:
     - "6001:8080"
    depends_on:
     - rubisdb
    labels:
      loadbalancer: "apache"
  rubisdb:
    container_name: rubisdb
    build:
      context: ./RubisDB
  rubisweb:
    container_name: rubisweb
    build:
      context: ./RubisWeb
    ports:
     - "6002:80"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
     - rubis
    security_opt:
     - label:disable
  rubisclient:
    container_name: rubisclient
    depends_on:
     - rubisdb
     - rubis
     - rubisweb
    build:
      context: ./RubisClient
    ports:
     - "6003:80"
    environment:
     - TARGET=emulator
